### ISSUE TITLE
Decimal Points

### ISSUE THREAD

**Issue by tekkydave** [moozzyk/TM1637Clock#1]
Hi. Have you discovered how to enable individual decimal points. I can enable both dots of the colon by or-ing the second digit with 0x80 and disable by doing the same to the third digit. I've done lots of googling but no luck.

**Comment by moozzyk** [comment]
To display the number you send the digits sequentially. If you want the decimal dot for the digit to be on you need to bitwise-OR the digit with 0x80.  In [this project](https://blog.3d-logic.com/2015/06/21/arduino-pomodoro-timer/) I use the decimal dot as a second indicator. Controlling the dot happens on this [line](https://github.com/moozzyk/ArduinoPomodoroTimer/blob/master/ArduinoPomodoroTimer/ArduinoPomodoroTimer.ino#L127) - exactly here:
```
digits[minutes % 10] | ((seconds & 0x01) << 7)
```
if the number of seconds is odd `seconds & 0x01` evaluates to 1. Then the number is shifted left to create 0x80 mask which is then bitwise OR-ed with the digit to display. If the number of seconds is even, the number to be shifted is 0 so the mask is 0 and after bitwise OR-ing it with the digit nothing changes. If you want to control the dot on a different position you need to apply similar logic to the digit at the position you want to control.
