### ISSUE TITLE
License

### ISSUE THREAD

**Issue by runvnc** [moozzyk/TM1637Clock#2]
Hello, thank you for your excellent code and the article on your blog.

If you don't mind, can you please add a license to this project (maybe MIT)?  Github says we get 0 rights without a license specified.  We have an Arduino prototype and I am hoping I can reuse a lot of the code in our commercial product (replacing the Arduino API calls with my own SAM3X8E code).  So even though it doesn't matter for the prototype, we can't have GPL in our next version, and so I need a way to do numbers and text on our LED that doesn't have any copyleft restriction.  

Its not a huge amount to sort of "paraphrase" but I am hoping you will put something like MIT so I can just fork or copy-paste and use yours as a starting point.  I will just need to add in a way to show some letters.

Thanks for your time.

**Comment by moozzyk** [comment]
GPL is out of question. I will add MIT license. I will try to do this later
today when I get home.

**Comment by runvnc** [comment]
Thank you so much!

**Comment by moozzyk** [comment]
0498e0ae6cc16b4625a488e537059f6f9266719f

**Comment by runvnc** [comment]
Thanks again. FYI I made it into a class and added scrolling text. [repo](https://github.com/runvnc/sevensegmenttm1637)
