### ISSUE TITLE
TM1637 0.56" does not work with NodeMCU

### ISSUE THREAD

**Issue by Dancopy** [moozzyk/TM1637Clock#3]
Hello Pawel, I have a question:
I have two TM1637 0.56 LED Display; They work with Arduino Uno but they don't work with ESP8266 NodeMCU. They even light up the red LED on the back of the board but the screen doesn't light up; Do you have any tip? Thanks

**Comment by moozzyk** [comment]
I have never tried using TM1637 with NodeMCU and unfortunately don't know how to make it work or why it doesn't work. Sorry!
